# Generated by Django 4.2.7 on 2024-12-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artists', models.CharField(max_length=255)),
                ('album_name', models.CharField(max_length=255)),
                ('track_name', models.CharField(max_length=255)),
                ('popularity', models.IntegerField()),
                ('duration_ms', models.IntegerField()),
                ('explicit', models.BooleanField()),
                ('danceability', models.FloatField()),
                ('energy', models.FloatField()),
                ('key', models.IntegerField()),
                ('loudness', models.FloatField()),
                ('mode', models.IntegerField()),
                ('speechiness', models.FloatField()),
                ('acousticness', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('liveness', models.FloatField()),
                ('valence', models.FloatField()),
                ('tempo', models.FloatField()),
                ('time_signature', models.IntegerField()),
                ('track_genre', models.CharField(max_length=255)),
                ('audioUrl', models.CharField(max_length=255)),
                ('imageUrl', models.CharField(max_length=255)),
            ],
        ),
    ]
